networks:
  diamonds-network-dev:

volumes:
  db-data-dev:

services:
  diamonds:
    build:
      context: ./../
      dockerfile: Dockerfile
    image: diamonds_are_forever_local
    container_name: diamonds_are_forever_local
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - diamonds-network-dev
    ports:
      - 8080:${DIAMONDS_APP_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DIAMONDS_APP_PORT=${DIAMONDS_APP_PORT}

  postgresql:
    image: 'postgres:${POSTGRES_VERSION}'
    networks:
      - diamonds-network-dev
    # TODO: add secrets management?
    # https://docs.docker.com/compose/how-tos/use-secrets/
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_USER}
    volumes:
      - ./../sql/:/docker-entrypoint-initdb.d:ro
      - db-data-dev:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diamonds"]
      interval: 2s
      timeout: 5s
      retries: 20

